### ISSUE TITLE
New decorator (to be released soon) is compatible with Ractive 0.6.1 but isn't with 0.7.2

### ISSUE THREAD

**Issue by paulocoghi** [ractivejs/plugin-template#7]
I created a Decorator Plugin for Bootstrap Select, inspired by Select2 Decorator
Preview gist: https://gist.github.com/paulocoghi/c1ed53db6adbfa8a1172

It runs well with Ractive 0.6.1 but it is conflicting with 0.7.2, throwing the error when used:

`TypeError: this.callback.call is not a function` in **ractive.js:2631:4**

I apologise since I am a beginner and still have to improve a lot.

**Comment by martypdx** [comment]
@paulocoghi instead of using the undocumented `node._ractive` you can now use `Ractive.getNodeInfo(node)` which will return an object with `{ ractive, keypath, index }`.  

[This line](https://gist.github.com/paulocoghi/c1ed53db6adbfa8a1172#file-ractive-decorators-bootstrap-select-js-L73) is probably no longer returning what you think it is, and that's causing the observe to try and juggle the arguments around - with end result being its `callback` is null

**Comment by paulocoghi** [comment]
Again, thank you very very much! Working on it right now!

**Comment by paulocoghi** [comment]
Done! I follow your instructions and changed the way it retrieve `node` information, and it's working like a charm :)

Gist updated (same url): https://gist.github.com/paulocoghi/c1ed53db6adbfa8a1172
